name: Main Branch CI

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write
  pull-requests: write
  checks: write

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-15
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true
      
      - name: Install Dependencies
        run: |
          bundle install
      
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      
      - name: Show Xcode Version
        run: xcodebuild -version
      
      - name: Show Available Simulators
        run: xcrun simctl list devices available
      
      - name: Build Project
        run: bundle exec fastlane build
      
      - name: Run Unit Tests
        run: bundle exec fastlane unit_tests
      
      - name: Run UI Tests
        run: bundle exec fastlane ui_tests
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: fastlane/test_output/
          retention-days: 30
      
      - name: Install Launchable CLI
        run: pip3 install --upgrade --break-system-packages launchable
      
      - name: Upload Code Coverage
        if: success()
        uses: codecov/codecov-action@v4
        with:
          files: ./fastlane/test_output/TripPlanner.xcresult
          fail_ci_if_error: false
          verbose: true
      
      - name: Comment on Commit
        if: success()
        run: |
          echo "✅ All tests passed on main branch!"
          echo "Build and tests completed successfully."

