name: Pull Request CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  launchable-tests:
    name: Launchable Intelligent Testing
    runs-on: macos-15
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Full history for Launchable
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true
      
      - name: Install Dependencies
        run: bundle install
      
      - name: Install Launchable CLI
        run: pip3 install --upgrade launchable
      
      - name: Verify Launchable Setup
        run: bundle exec fastlane launchable_verify
        env:
          LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
      
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      
      - name: Show Xcode Version
        run: xcodebuild -version
      
      - name: Show Available Simulators
        run: xcrun simctl list devices available
      
      - name: Record Build with Launchable
        run: bundle exec fastlane launchable_record_build
        env:
          LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
          GITHUB_RUN_ID: ${{ github.run_id }}
      
      - name: Run Launchable Intelligent Tests
        run: bundle exec fastlane launchable_test
        env:
          LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
          GITHUB_RUN_ID: ${{ github.run_id }}
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: launchable-test-results
          path: fastlane/test_output/
          retention-days: 30
      
      - name: Get Launchable Insights
        if: always()
        run: |
          launchable inspect tests --session $LAUNCHABLE_SESSION_ID > launchable_insights.txt || true
          cat launchable_insights.txt
        env:
          LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}
      
      - name: Comment Test Results on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let comment = '🧠 **Launchable Intelligent Testing**\n\n';
            
            try {
              const insights = fs.readFileSync('launchable_insights.txt', 'utf8');
              comment += '```\n' + insights + '\n```\n';
            } catch (e) {
              comment += '✅ Tests completed successfully!\n';
            }
            
            comment += '\n[View detailed insights on Launchable](https://app.launchableinc.com)';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
  
  full-tests-fallback:
    name: Full Test Suite (Fallback)
    runs-on: macos-15
    needs: launchable-tests
    if: failure() # Only if Launchable tests fail
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true
      
      - name: Install Dependencies
        run: bundle install
      
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      
      - name: Build for Testing
        run: bundle exec fastlane build_for_testing
      
      - name: Run UI Tests
        run: bundle exec fastlane ui_tests
      
      - name: Upload UI Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: fastlane/test_output/ui_tests/
          retention-days: 30
      
      - name: Upload Screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-screenshots
          path: fastlane/screenshots/
          retention-days: 7
      
      - name: Comment Test Results on PR
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const testResults = '✅ UI tests completed!';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: testResults
            });
  
  build-check:
    name: Build Check
    runs-on: macos-15
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true
      
      - name: Install Dependencies
        run: bundle install
      
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      
      - name: Build Project
        run: bundle exec fastlane build
      
      - name: Comment Build Status on PR
        if: success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ Build succeeded!'
            });

